'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Chatbox from "./components/chatbox";
import AiAssistant from "./components/aiAssistant";
import { usePathname } from "next/navigation";
import { useEffect } from "react";
import { initGA, logPageView } from "../../lib/ga/gtag";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  useEffect(() => {
    initGA();
    logPageView(pathname);
    window.addEventListener('routeChangeComplete', () => logPageView(pathname));

    return () => {
      window.removeEventListener('routeChangeComplete', () => logPageView(pathname));
    };
  }, [pathname]);
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className="relative max-w-7xl mx-auto  min-h-screen"
        >
          <Navbar />
          <AiAssistant />
          {/* <Chatbox /> */}
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
