import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Chatbox from "./components/chatbox";
import AiAssistant from "./components/aiAssistant";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className="relative max-w-7xl mx-auto  min-h-screen"
        >
          <Navbar />
          <AiAssistant />
          {/* <Chatbox /> */}
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
